coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
flags:
  unit:
    paths:
      - src/
  com:
    paths:
      - src/
    carryforward: true
