"""First-class workbook editing API for ExStruct."""

from __future__ import annotations

from .api import make_workbook, patch_workbook
from .chart_types import (
    CHART_TYPE_ALIASES,
    CHART_TYPE_TO_COM_ID,
    SUPPORTED_CHART_TYPES,
    SUPPORTED_CHART_TYPES_CSV,
    SUPPORTED_CHART_TYPES_SET,
    normalize_chart_type,
    resolve_chart_type_id,
)
from .errors import PatchOpError
from .models import (
    AlignmentSnapshot,
    BorderSideSnapshot,
    BorderSnapshot,
    ColumnDimensionSnapshot,
    DesignSnapshot,
    FillSnapshot,
    FontSnapshot,
    FormulaIssue,
    MakeRequest,
    MergeStateSnapshot,
    OpenpyxlEngineResult,
    OpenpyxlWorksheetProtocol,
    PatchDiffItem,
    PatchErrorDetail,
    PatchOp,
    PatchRequest,
    PatchResult,
    PatchValue,
    RowDimensionSnapshot,
    XlwingsRangeProtocol,
)
from .normalize import (
    alias_to_canonical_with_conflict_check,
    build_missing_sheet_message,
    build_patch_op_error_message,
    coerce_patch_ops,
    normalize_draw_grid_border_range,
    normalize_patch_op_aliases,
    normalize_top_level_sheet,
    parse_patch_op_json,
    resolve_top_level_sheet_for_payload,
)
from .op_schema import (
    PatchOpSchema,
    build_patch_tool_mini_schema,
    get_patch_op_schema,
    list_patch_op_schemas,
    schema_with_sheet_resolution_rules,
)
from .specs import PATCH_OP_SPECS, PatchOpSpec, get_alias_map_for_op
from .types import (
    FormulaIssueCode,
    FormulaIssueLevel,
    HorizontalAlignType,
    OnConflictPolicy,
    PatchBackend,
    PatchEngine,
    PatchOpType,
    PatchStatus,
    PatchValueKind,
    VerticalAlignType,
)

__all__ = [
    "AlignmentSnapshot",
    "BorderSideSnapshot",
    "BorderSnapshot",
    "CHART_TYPE_ALIASES",
    "CHART_TYPE_TO_COM_ID",
    "ColumnDimensionSnapshot",
    "DesignSnapshot",
    "FillSnapshot",
    "FontSnapshot",
    "FormulaIssue",
    "FormulaIssueCode",
    "FormulaIssueLevel",
    "HorizontalAlignType",
    "MakeRequest",
    "MergeStateSnapshot",
    "OnConflictPolicy",
    "OpenpyxlEngineResult",
    "OpenpyxlWorksheetProtocol",
    "PATCH_OP_SPECS",
    "PatchBackend",
    "PatchDiffItem",
    "PatchEngine",
    "PatchErrorDetail",
    "PatchOp",
    "PatchOpError",
    "PatchOpSchema",
    "PatchOpSpec",
    "PatchOpType",
    "PatchRequest",
    "PatchResult",
    "PatchStatus",
    "PatchValue",
    "PatchValueKind",
    "RowDimensionSnapshot",
    "SUPPORTED_CHART_TYPES",
    "SUPPORTED_CHART_TYPES_CSV",
    "SUPPORTED_CHART_TYPES_SET",
    "VerticalAlignType",
    "XlwingsRangeProtocol",
    "alias_to_canonical_with_conflict_check",
    "build_missing_sheet_message",
    "build_patch_op_error_message",
    "build_patch_tool_mini_schema",
    "coerce_patch_ops",
    "get_alias_map_for_op",
    "get_patch_op_schema",
    "list_patch_op_schemas",
    "make_workbook",
    "normalize_chart_type",
    "normalize_draw_grid_border_range",
    "normalize_patch_op_aliases",
    "normalize_top_level_sheet",
    "parse_patch_op_json",
    "patch_workbook",
    "resolve_chart_type_id",
    "resolve_top_level_sheet_for_payload",
    "schema_with_sheet_resolution_rules",
]
