"""Compatibility shim for legacy runtime helpers."""

from __future__ import annotations

from exstruct.edit.runtime import (
    ComAvailability,
    PatchOpError,
    allow_auto_openpyxl_fallback,
    append_large_ops_warning,
    apply_conflict_policy,
    build_make_seed_path,
    contains_apply_table_style_op,
    contains_create_chart_op,
    contains_design_ops,
    create_seed_workbook,
    ensure_output_dir,
    ensure_supported_extension,
    expand_range_coordinates,
    get_com_availability,
    requires_openpyxl_backend,
    resolve_input_path,
    resolve_make_initial_sheet_name,
    resolve_make_output_path,
    resolve_output_path,
    select_patch_engine,
    validate_make_request_constraints,
)

__all__ = [
    "PatchOpError",
    "allow_auto_openpyxl_fallback",
    "append_large_ops_warning",
    "apply_conflict_policy",
    "build_make_seed_path",
    "contains_apply_table_style_op",
    "contains_create_chart_op",
    "contains_design_ops",
    "create_seed_workbook",
    "ensure_output_dir",
    "ensure_supported_extension",
    "expand_range_coordinates",
    "get_com_availability",
    "requires_openpyxl_backend",
    "resolve_input_path",
    "resolve_make_initial_sheet_name",
    "resolve_make_output_path",
    "resolve_output_path",
    "select_patch_engine",
    "validate_make_request_constraints",
    "ComAvailability",
]
